### ISSUE TITLE
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState when viewing duplicate codes → going anywhere

### ISSUE THREAD

**Issue by Mattwmaster58** [CMPUT301W22T00/QRHunt#435]
- scan code
 - scan code again, then immediately go to leaderboard. app crashes
```java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bigyoshi.qrhunt, PID: 18768
    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1551)
        at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1591)
        at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
        at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
        at androidx.fragment.app.DialogFragment.show(DialogFragment.java:261)
        at com.bigyoshi.qrhunt.qr.QrCodeProcessor.lambda$processQRCode$0$com-bigyoshi-qrhunt-qr-QrCodeProcessor(QrCodeProcessor.java:140)
        at com.bigyoshi.qrhunt.qr.QrCodeProcessor$$ExternalSyntheticLambda0.onComplete(Unknown Source:4)
        at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
        ```

It's because you're trying to dismiss the dialog after the fragment gets rekt

**Comment by kezzayuno** [comment]
Cannot be reproduced on the main branch, for now, I will close it
